trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
   major: 0
   minor: 0
   ver: $[counter("", 0)]
   name: $(major).$(minor).$(ver)
name: $(major).$(minor).$(ver)

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker registry'
    repository: 'online-users-monitor'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(name)
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s vsm'
    command: 'set'
    arguments: 'image deployments/online-users-monitor hardhu.azurecr.io/vsm/online-users-monitor:$(name)'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'