trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
   major: 0
   minor: 0
   ver: $[counter('', 0)]
   name: $(major).$(minor).$(ver)
name: $(major).$(minor).$(ver)

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package spring-boot:repackage'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  inputs:
    containerRegistry: 'docker registry'
    repository: 'online-users-monitor'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(name)
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s vsm'
    namespace: 'vsm'
    command: 'set'
    arguments: 'image deployments/online-users-monitor online=hardhu.azurecr.io/vsm/online-users-monitor:$(name)'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure dla studentów(7a8dcb4c-7baf-4bb5-9807-9a189e848aec)'
    azureContainerRegistry: 'hardhu.azurecr.io'